### ISSUE TITLE
getTaxText() twice

### ISSUE THREAD

**Issue by PierreCorell** [Magenerds/GermanLaw#2]
Inside productdetails, but not in lists / categories, $block->getTaxText() ( \Magenerds\GermanLaw\Block\AfterPrice ) is executed twice, though it is not directly from inside the module which I searched through. Maybe Magento´s behaviour changed (also because https://github.com/Magenerds/BasePrice/issues/2 is a similar issue in another module)...?

For a quick and dirty fix you can use css as seen in the screenshot
`.tax-details + .tax-details { display: none; }`

Best regards, Pierre.

![pco-fm_2016-12-09_090822](https://cloud.githubusercontent.com/assets/3313934/21042062/83612ace-bdef-11e6-8839-d154cd83a41d.png)

**Comment by sydekumf** [comment]
The problem was that Magento wants to render the tier prices but as the product does not have tier prices it is empty, therefore it looks like duplicate rendering. There is a fix, which only displays the text, if tier prices are available: https://github.com/Magenerds/GermanLaw/commit/65127c86acf9686e829dc5c19b60573fd32f3ff8
