### ISSUE TITLE
Tax rate showing up multiple times & not showing percentage on some cases

### ISSUE THREAD

**Issue by chaot1x** [Magenerds/GermanLaw#3]
Tax rate is showing up multiple times in product page, in simple/configurable products it is showing up twice, one next to price and one next to submit button.

As we know that grouped products has issues with tax rates (magento bug) and in this case it is not showing tax rate percentage, but it should show atleast 0%, for example there is a text "Tax rate %s" on products like simple/configurable it would show "Tax rate 20%" on grouped it shows up like this "Tax rate"

Tax rate text is showing up twice for every grouped product and one extra at the end of grouped product table.

**Comment by sydekumf** [comment]
The problem was that Magento wants to render the tier prices but as the product does not have tier prices it is empty, therefore it looks like duplicate rendering. There is a fix, which only displays the text, if tier prices are available: https://github.com/Magenerds/GermanLaw/commit/65127c86acf9686e829dc5c19b60573fd32f3ff8

I don't think that showing 0% tax rate is legal. Also in Germany it is the law to display the text whenever are price is rendered.
