### ISSUE TITLE
singel % symbol noch possible to display

### ISSUE THREAD

**Issue by Tibi38** [Magenerds/GermanLaw#7]
Hi,
i tried to fill in following text in Tax-Text: Inkl. 19 % Mwst. zzgl. [ Versand ]
But than the Upper M is disappearing. How can I enter a fix Text with % - Symbol?
I tried already with HTML-eqis but also not going neither the \ to mask it.

**Comment by sydekumf** [comment]
Hi there,
indeed this is not supported in the first place. It is intended to calculate the tax from its product. I think you want to insert a fixed tax 19% for all products? Can you tell me why you do this?
The extension is written so that it calculates the tax of the product and displays it: https://github.com/Magenerds/GermanLaw/blob/master/Block/AfterPrice.php#L124 Can it be that you forgot to set the tax class to this product? Then the tax will not get rendered.

As the documentation says: *Use %s in order to insert tax* so the code actually searches for *%s* and replaces it with the calculated tax. As you use the character *%* it tries to replace it. But as I said, that was not intended, so maybe it helps you configuring the tax classes of your products? :-)

If you have any further questions about this, please ask, I would also love to hear why you used a fixed tax value 19%.
